/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import matematica.FuncaoObjetivo;
import matematica.MetodoPL;
import matematica.Restricao;

/**
 *
 * @author william
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_Calcular = new javax.swing.JButton();
        combo_ineq3_isMenor = new javax.swing.JComboBox<>();
        txt_ineq4_c = new javax.swing.JTextField();
        combo_ineq4_isMenor = new javax.swing.JComboBox<>();
        txt_ineq4_a = new javax.swing.JTextField();
        txt_ineq3_a = new javax.swing.JTextField();
        txt_ineq4_b = new javax.swing.JTextField();
        txt_ineq3_b = new javax.swing.JTextField();
        txt_ineq5_c = new javax.swing.JTextField();
        combo_ineq5_isMenor = new javax.swing.JComboBox<>();
        txt_ineq6_c = new javax.swing.JTextField();
        combo_ineq6_isMenor = new javax.swing.JComboBox<>();
        txt_ineq6_a = new javax.swing.JTextField();
        txt_ineq5_a = new javax.swing.JTextField();
        txt_ineq6_b = new javax.swing.JTextField();
        txt_ineq5_b = new javax.swing.JTextField();
        txt_ineq7_c = new javax.swing.JTextField();
        combo_ineq7_isMenor = new javax.swing.JComboBox<>();
        txt_ineq8_c = new javax.swing.JTextField();
        combo_ineq8_isMenor = new javax.swing.JComboBox<>();
        txt_ineq8_a = new javax.swing.JTextField();
        txt_ineq7_a = new javax.swing.JTextField();
        txt_ineq8_b = new javax.swing.JTextField();
        txt_ineq7_b = new javax.swing.JTextField();
        txt_ineq9_c = new javax.swing.JTextField();
        combo_ineq9_isMenor = new javax.swing.JComboBox<>();
        txt_ineq10_c = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        combo_ineq10_isMenor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_ineq10_a = new javax.swing.JTextField();
        txt_ineq1_a = new javax.swing.JTextField();
        txt_ineq9_a = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ineq10_b = new javax.swing.JTextField();
        txt_ineq1_b = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ineq1_c = new javax.swing.JTextField();
        combo_ineq1_isMenor = new javax.swing.JComboBox<>();
        txt_ineq9_b = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbl_pontoX = new javax.swing.JLabel();
        lbl_pontoY = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_fo_b = new javax.swing.JLabel();
        txt_fo_a = new javax.swing.JTextField();
        txt_fo_b = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        combo_fo_isMax = new javax.swing.JComboBox<>();
        txt_ineq2_c = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        combo_ineq2_isMenor = new javax.swing.JComboBox<>();
        txt_ineq2_a = new javax.swing.JTextField();
        txt_ineq2_b = new javax.swing.JTextField();
        txt_ineq3_c = new javax.swing.JTextField();
        btn_limpar = new javax.swing.JButton();
        lbl_valor_Otimo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_msg = new javax.swing.JLabel();
        lbl_X_Otimo = new javax.swing.JLabel();
        lbl_Y_Otimo = new javax.swing.JLabel();
        lbl_Valor_Otimo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_def_X = new javax.swing.JTextField();
        txt_def_Y = new javax.swing.JTextField();
        txt_def_FO = new javax.swing.JTextField();
        txt_unid_X = new javax.swing.JTextField();
        txt_unid_Y = new javax.swing.JTextField();
        txt_unid_FO = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_unid_X_Otimo = new javax.swing.JLabel();
        lbl_unid_Y_Otimo = new javax.swing.JLabel();
        lbl_unid_FO_Otimo = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Calcular.setText("Calcular");
        lbl_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_CalcularActionPerformed(evt);
            }
        });

        combo_ineq3_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        combo_ineq4_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        txt_ineq4_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq4_aActionPerformed(evt);
            }
        });

        txt_ineq4_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq4_bActionPerformed(evt);
            }
        });

        txt_ineq3_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq3_bActionPerformed(evt);
            }
        });

        combo_ineq5_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        combo_ineq6_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        txt_ineq6_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq6_bActionPerformed(evt);
            }
        });

        txt_ineq5_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq5_bActionPerformed(evt);
            }
        });

        combo_ineq7_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        combo_ineq8_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        txt_ineq8_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq8_bActionPerformed(evt);
            }
        });

        txt_ineq7_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq7_bActionPerformed(evt);
            }
        });

        combo_ineq9_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Programação Linear de duas variáveis");

        combo_ineq10_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("a");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("b");

        txt_ineq10_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq10_bActionPerformed(evt);
            }
        });

        txt_ineq1_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq1_bActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("c");

        combo_ineq1_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        txt_ineq9_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq9_bActionPerformed(evt);
            }
        });

        jLabel5.setText("Solução:");

        lbl_pontoX.setText("variável X:");

        lbl_pontoY.setText("variável Y:");

        jLabel7.setText("Função Objetivo = ax + by");

        lbl_fo_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fo_b.setText("b");

        txt_fo_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fo_aActionPerformed(evt);
            }
        });

        jLabel9.setText("Restrições:                              ax + by ≤ c      ou     ax + by ≥ c");

        combo_fo_isMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maximização", "Minimização" }));
        combo_fo_isMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_fo_isMaxActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("a");

        combo_ineq2_isMenor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "≤", "≥" }));

        txt_ineq2_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ineq2_bActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        lbl_valor_Otimo.setText("Valor Ótimo:");

        jLabel3.setText("OBS:");

        lbl_msg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_msg.setForeground(new java.awt.Color(255, 0, 0));

        lbl_X_Otimo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_X_Otimo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_X_Otimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_X_Otimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Y_Otimo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Y_Otimo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Y_Otimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Y_Otimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Valor_Otimo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Valor_Otimo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_Valor_Otimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Valor_Otimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Definição de variáveis e da Função Objetivo");

        jLabel10.setText("variável X");

        jLabel11.setText("variável Y");

        jLabel12.setText("Função Objetivo");

        jLabel14.setText("Descrição");

        jLabel15.setText("Unidade");

        txt_def_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_def_YActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_pontoX, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_pontoY, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_valor_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Valor_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_X_Otimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Y_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_unid_Y_Otimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_unid_FO_Otimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_unid_X_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Calcular)
                            .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(182, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_msg, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_def_Y)
                            .addComponent(txt_def_FO)
                            .addComponent(txt_def_X, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_unid_X, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_unid_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_unid_FO, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(txt_fo_a, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_fo_b, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(combo_fo_isMax, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_fo_b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_ineq3_a, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(txt_ineq6_a)
                            .addComponent(txt_ineq5_a)
                            .addComponent(txt_ineq7_a)
                            .addComponent(txt_ineq8_a)
                            .addComponent(txt_ineq9_a)
                            .addComponent(txt_ineq10_a)
                            .addComponent(txt_ineq2_a)
                            .addComponent(txt_ineq1_a)
                            .addComponent(txt_ineq4_a))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ineq1_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq2_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq4_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq3_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_ineq5_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ineq6_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ineq7_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ineq8_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ineq9_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ineq10_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_ineq9_isMenor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combo_ineq7_isMenor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq1_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq2_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq5_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq3_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq4_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq6_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq8_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(combo_ineq10_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ineq9_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq7_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq1_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq2_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq5_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq3_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq4_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq6_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq8_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ineq10_c, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel14)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_def_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unid_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_def_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unid_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_def_FO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unid_FO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_fo_b))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fo_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fo_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_fo_isMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq1_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq1_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq1_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq1_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq2_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq2_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq2_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq2_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq3_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq3_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq3_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq3_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ineq4_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_ineq4_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_ineq4_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_ineq4_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq5_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq5_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq5_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq5_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq6_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq6_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq6_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq6_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq7_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq7_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq7_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq7_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq8_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq8_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq8_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq8_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq9_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq9_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq9_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq9_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ineq10_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq10_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_ineq10_isMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ineq10_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_X_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Y_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 2, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbl_pontoX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5))
                                            .addComponent(lbl_unid_X_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_pontoY, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_unid_Y_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Valor_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_valor_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_unid_FO_Otimo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_def_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_def_YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_def_YActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:

        
        txt_def_X.setText("");
        txt_def_Y.setText("");
        txt_def_FO.setText("");
        
        txt_unid_X.setText("");
        txt_unid_Y.setText("");
        txt_unid_FO.setText("");
        
        txt_fo_a.setText("");
        txt_fo_b.setText("");

        txt_ineq1_a.setText("");
        txt_ineq1_b.setText("");
        txt_ineq1_c.setText("");

        txt_ineq2_a.setText("");
        txt_ineq2_b.setText("");
        txt_ineq2_c.setText("");

        txt_ineq3_a.setText("");
        txt_ineq3_b.setText("");
        txt_ineq3_c.setText("");

        txt_ineq4_a.setText("");
        txt_ineq4_b.setText("");
        txt_ineq4_c.setText("");

        txt_ineq5_a.setText("");
        txt_ineq5_b.setText("");
        txt_ineq5_c.setText("");

        txt_ineq6_a.setText("");
        txt_ineq6_b.setText("");
        txt_ineq6_c.setText("");

        txt_ineq7_a.setText("");
        txt_ineq7_b.setText("");
        txt_ineq7_c.setText("");

        txt_ineq8_a.setText("");
        txt_ineq8_b.setText("");
        txt_ineq8_c.setText("");

        txt_ineq9_a.setText("");
        txt_ineq9_b.setText("");
        txt_ineq9_c.setText("");

        txt_ineq10_a.setText("");
        txt_ineq10_b.setText("");
        txt_ineq10_c.setText("");

        lbl_X_Otimo.setText("");
        lbl_Y_Otimo.setText("");
        lbl_Valor_Otimo.setText("");
        
        lbl_unid_X_Otimo.setText("");
        lbl_unid_Y_Otimo.setText("");
        lbl_unid_FO_Otimo.setText("");
        lbl_msg.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void txt_ineq2_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq2_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq2_bActionPerformed

    private void combo_fo_isMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_fo_isMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_fo_isMaxActionPerformed

    private void txt_fo_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fo_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fo_aActionPerformed

    private void txt_ineq9_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq9_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq9_bActionPerformed

    private void txt_ineq1_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq1_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq1_bActionPerformed

    private void txt_ineq10_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq10_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq10_bActionPerformed

    private void txt_ineq7_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq7_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq7_bActionPerformed

    private void txt_ineq8_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq8_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq8_bActionPerformed

    private void txt_ineq5_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq5_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq5_bActionPerformed

    private void txt_ineq6_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq6_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq6_bActionPerformed

    private void txt_ineq3_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq3_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq3_bActionPerformed

    private void txt_ineq4_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq4_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq4_bActionPerformed

    private void txt_ineq4_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ineq4_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ineq4_aActionPerformed

    private void lbl_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_CalcularActionPerformed
        // TODO add your handling code here:
        //objeto 'fo' que armazenará dados da Função Objetivo
        FuncaoObjetivo fo = new FuncaoObjetivo();
        //objeto 'metodo' que instancia a classe para resolução do problema de Programação Linear
        MetodoPL metodo = new MetodoPL();
        //objeto para resultado que armazena mensagem e objeto de restrição
        Resultado resultado = new Resultado();
        List<Resultado> listaResultados = new ArrayList<>();
        Restricao restr;
        List<Restricao> listaRestricoes = new ArrayList<>();
        String msg;
        StringBuilder mensagem = new StringBuilder();

        //declaração inicial de pontos e valores ótimos
        String x_otimo="";
        String y_otimo="";
        String valor_otimo="";

        msg="";
        //armazenagem da Função Objetivo ax + by
        String valor_fo = txt_fo_a.getText();
        //armazenagem do coefiente 'a' da FO
        if(valor_fo.matches("-?\\d+(\\.\\d+)?"))
            fo.setA(converteString(valor_fo));
        else
            msg= "erro de consistência no campo da função objetivo";
        //armazenagem do coefiente 'b' da FO
        valor_fo=txt_fo_b.getText();
        if(valor_fo.matches("-?\\d+(\\.\\d+)?"))
            fo.setB(converteString(valor_fo));
        else
            msg = "erro de consistencia no campo da funcão objetivo";
        //armazenagem se FO é do Maximização ou Minimização
        fo.setTipo(combo_fo_isMax.getSelectedItem().toString());
        //armazenando objeto com dados da função objetivo no metodo da PL
        metodo.setFo(fo);
        //armazenando mensagens de erro na String Builder que deverá ser exibido na tela
        mensagem.append(msg);

        //armezenado dados de inequações da Restrição do problema em uma lista
        resultado = validarCampoRestricao(txt_ineq1_a.getText(),txt_ineq1_b.getText(),txt_ineq1_c.getText(),combo_ineq1_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq2_a.getText(),txt_ineq2_b.getText(),txt_ineq2_c.getText(),combo_ineq2_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq3_a.getText(),txt_ineq3_b.getText(),txt_ineq3_c.getText(),combo_ineq3_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq4_a.getText(),txt_ineq4_b.getText(),txt_ineq4_c.getText(),combo_ineq4_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq5_a.getText(),txt_ineq5_b.getText(),txt_ineq5_c.getText(),combo_ineq5_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq6_a.getText(),txt_ineq6_b.getText(),txt_ineq6_c.getText(),combo_ineq6_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq7_a.getText(),txt_ineq7_b.getText(),txt_ineq7_c.getText(),combo_ineq7_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq8_a.getText(),txt_ineq8_b.getText(),txt_ineq8_c.getText(),combo_ineq8_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq9_a.getText(),txt_ineq9_b.getText(),txt_ineq9_c.getText(),combo_ineq9_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);
        resultado = validarCampoRestricao(txt_ineq10_a.getText(),txt_ineq10_b.getText(),txt_ineq10_c.getText(),combo_ineq10_isMenor.getSelectedItem().toString());
        listaResultados.add(resultado);

        //gerando condição para que só seja armazenado inequações de campos preenchidos na tela
        for(int i=0;i<listaResultados.size();i++)
        {
            mensagem.append(listaResultados.get(i).getMsg());
            if(!(listaResultados.get(i).getRestricao().getA()==0&&listaResultados.get(i).getRestricao().getB()==0&&listaResultados.get(i).getRestricao().getC()==0))
            listaRestricoes.add(listaResultados.get(i).getRestricao());
        }

        lbl_X_Otimo.setText("");
        lbl_Y_Otimo.setText("");
        lbl_Valor_Otimo.setText("");
        //recuperando mensagem de erro armazenada na String Builder
        msg=mensagem.toString();

        //caso nao haja mensagem de erro
        if(msg.equals(""))
        {
            metodo.setListaRestricoes(listaRestricoes);
            metodo.calcular();
            System.out.println("Ponto X: " + metodo.getX_Otimo());
            System.out.println("Ponto Y: " + metodo.getY_Otimo());
            System.out.println("Valor Final: " + metodo.getValor_Otimo());

            x_otimo = String.format("%.2f", metodo.getX_Otimo());
            y_otimo = String.format("%.2f", metodo.getY_Otimo());
            valor_otimo = String.format("%.2f", metodo.getValor_Otimo());

            if(Math.abs(metodo.getX_Otimo())==2e12||Math.abs(metodo.getY_Otimo())==2e12)
            {
                msg="Solução não converge. Resposta infinita";
            }
            else{
                lbl_X_Otimo.setText(x_otimo);
                lbl_Y_Otimo.setText(y_otimo);
                lbl_Valor_Otimo.setText(valor_otimo);
                lbl_unid_X_Otimo.setText(txt_unid_X.getText());
                lbl_unid_Y_Otimo.setText(txt_unid_Y.getText());
                lbl_unid_FO_Otimo.setText(txt_unid_FO.getText());
            }

        }
        lbl_msg.setText(msg);
    }//GEN-LAST:event_lbl_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    public Resultado validarCampoRestricao(String ineq_a,String ineq_b,String ineq_c, String ineq_simbol){
        Resultado resultado = new Resultado();
        String msg = "";
        Restricao restr = new Restricao();
        if(ineq_a.isEmpty()&&ineq_b.isEmpty()&&!ineq_c.isEmpty())
            msg="restrição inválida";
        else if((!ineq_a.isEmpty()||!ineq_b.isEmpty())&&ineq_c.isEmpty())
            msg="campo c vazio";
        else if((!ineq_a.isEmpty()&&!ineq_a.matches("-?\\d+(\\.\\d+)?"))
                ||(!ineq_b.isEmpty()&&!ineq_b.matches("-?\\d+(\\.\\d+)?"))
                ||(!ineq_c.isEmpty()&&!ineq_c.matches("-?\\d+(\\.\\d+)?")))
            msg="erro de consistência no campo da restrição";
        else if((!ineq_a.isEmpty()||!ineq_b.isEmpty())&&!ineq_c.isEmpty())
        {
            restr.setA(converteString(ineq_a));
            restr.setB(converteString(ineq_b));
            restr.setC(converteString(ineq_c));
            restr.setSimboloIneq(ineq_simbol);
        }
        resultado.setMsg(msg);
        resultado.setRestricao(restr);
        return resultado;
    }
    
    //se o campo estiver vazio, retorna valor 0
    public double converteString(String strValor)
    {
        double numValor;
        if(!strValor.isEmpty())
            numValor = Double.parseDouble(strValor);
        else
            numValor=0;
        return numValor;
    }
    
           
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpar;
    private javax.swing.JComboBox<String> combo_fo_isMax;
    private javax.swing.JComboBox<String> combo_ineq10_isMenor;
    private javax.swing.JComboBox<String> combo_ineq1_isMenor;
    private javax.swing.JComboBox<String> combo_ineq2_isMenor;
    private javax.swing.JComboBox<String> combo_ineq3_isMenor;
    private javax.swing.JComboBox<String> combo_ineq4_isMenor;
    private javax.swing.JComboBox<String> combo_ineq5_isMenor;
    private javax.swing.JComboBox<String> combo_ineq6_isMenor;
    private javax.swing.JComboBox<String> combo_ineq7_isMenor;
    private javax.swing.JComboBox<String> combo_ineq8_isMenor;
    private javax.swing.JComboBox<String> combo_ineq9_isMenor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton lbl_Calcular;
    private javax.swing.JLabel lbl_Valor_Otimo;
    private javax.swing.JLabel lbl_X_Otimo;
    private javax.swing.JLabel lbl_Y_Otimo;
    private javax.swing.JLabel lbl_fo_b;
    private javax.swing.JLabel lbl_msg;
    private javax.swing.JLabel lbl_pontoX;
    private javax.swing.JLabel lbl_pontoY;
    private javax.swing.JLabel lbl_unid_FO_Otimo;
    private javax.swing.JLabel lbl_unid_X_Otimo;
    private javax.swing.JLabel lbl_unid_Y_Otimo;
    private javax.swing.JLabel lbl_valor_Otimo;
    private javax.swing.JTextField txt_def_FO;
    private javax.swing.JTextField txt_def_X;
    private javax.swing.JTextField txt_def_Y;
    private javax.swing.JTextField txt_fo_a;
    private javax.swing.JTextField txt_fo_b;
    private javax.swing.JTextField txt_ineq10_a;
    private javax.swing.JTextField txt_ineq10_b;
    private javax.swing.JTextField txt_ineq10_c;
    private javax.swing.JTextField txt_ineq1_a;
    private javax.swing.JTextField txt_ineq1_b;
    private javax.swing.JTextField txt_ineq1_c;
    private javax.swing.JTextField txt_ineq2_a;
    private javax.swing.JTextField txt_ineq2_b;
    private javax.swing.JTextField txt_ineq2_c;
    private javax.swing.JTextField txt_ineq3_a;
    private javax.swing.JTextField txt_ineq3_b;
    private javax.swing.JTextField txt_ineq3_c;
    private javax.swing.JTextField txt_ineq4_a;
    private javax.swing.JTextField txt_ineq4_b;
    private javax.swing.JTextField txt_ineq4_c;
    private javax.swing.JTextField txt_ineq5_a;
    private javax.swing.JTextField txt_ineq5_b;
    private javax.swing.JTextField txt_ineq5_c;
    private javax.swing.JTextField txt_ineq6_a;
    private javax.swing.JTextField txt_ineq6_b;
    private javax.swing.JTextField txt_ineq6_c;
    private javax.swing.JTextField txt_ineq7_a;
    private javax.swing.JTextField txt_ineq7_b;
    private javax.swing.JTextField txt_ineq7_c;
    private javax.swing.JTextField txt_ineq8_a;
    private javax.swing.JTextField txt_ineq8_b;
    private javax.swing.JTextField txt_ineq8_c;
    private javax.swing.JTextField txt_ineq9_a;
    private javax.swing.JTextField txt_ineq9_b;
    private javax.swing.JTextField txt_ineq9_c;
    private javax.swing.JTextField txt_unid_FO;
    private javax.swing.JTextField txt_unid_X;
    private javax.swing.JTextField txt_unid_Y;
    // End of variables declaration//GEN-END:variables
}
